In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts

In [ ]:
df = pd.read_csv("Advertising.csv")
df.head(3)

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3

In [ ]:
df = df.drop("Unnamed: 0", axis=1)

In [ ]:
df.head(2)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4

In [ ]:
x = df.drop("Sales", axis=1)
y = df['Sales']

print(x.shape)
print(y.shape)

(200, 3)
(200,)

In [ ]:
x_train,x_test,y_train,y_test = tts(x,y, test_size=0.2, random_state=42)

In [ ]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
print("coeff:",lr.coef_)
print("intercept:",lr.intercept_)

coeff: [0.04472952 0.18919505 0.00276111]
intercept: 2.979067338122629

In [ ]:
y_pred = lr.predict(x_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
print(r2)

0.899438024100912

<h1> Using Class

In [ ]:
x_train.shape

(160, 3)

coeff: [0.04472952 0.18919505 0.00276111]
intercept: 2.979067338122629

In [ ]:
class SGDRegressor:

  def __init__(self,learning_rate=0.01,epochs=100):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None

  def fit(self,x_train,y_train):

    # initializing random coef & intercept
    self.coef_ = np.zeros(x_train.shape[1])
    self.intercept_ = 0

    print(self.coef_,self.intercept_)

    for i in range(self.epochs):
      for j in range(x_train.shape[0]):

        idx = np.random.randint(0,x_train.shape[0])
        # vectorization
        y_hat = np.dot(x_train.iloc[idx], self.coef_) + self.intercept_

        intercept_der = -2 * (y_train.iloc[idx] - y_hat)
        self.intercept_ -= self.learning_rate * intercept_der

        coef_der = -2 * np.dot((y_train.iloc[idx] - y_hat), x_train.iloc[idx])
        self.coef_ -= self.learning_rate * coef_der

        # print control
      if i < 200 or i >= self.epochs - 200:
            print(f"epoch={i}, coef={self.coef_}, intercept={self.intercept_}")


  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [ ]:
gd = SGDRegressor(learning_rate=0.000019,epochs=90)

In [ ]:
gd.fit(x_train,y_train)

[0. 0. 0.] 0
epoch=0, coef=[0.05608545 0.11893377 0.05319536], intercept=0.003324221210687631
epoch=1, coef=[0.02004131 0.19478457 0.061454  ], intercept=0.007431357991264664
epoch=2, coef=[0.03498429 0.21154623 0.01298647], intercept=0.009595655426827051
epoch=3, coef=[0.05750352 0.19055101 0.0009114 ], intercept=0.010897722296437318
epoch=4, coef=[0.03516878 0.2251823  0.01439571], intercept=0.013455943202712537
epoch=5, coef=[0.1065213  0.21386968 0.03473104], intercept=0.016497135333771628
epoch=6, coef=[0.06081155 0.19245788 0.02172243], intercept=0.019332400005459865
epoch=7, coef=[0.06024993 0.23454467 0.00472077], intercept=0.021199708041950358
epoch=8, coef=[ 0.05685931  0.26407003 -0.00413571], intercept=0.023387766004623528
epoch=9, coef=[ 0.05262555  0.24531214 -0.00137911], intercept=0.02665712827076665
epoch=10, coef=[ 0.04323917  0.23894997 -0.00763448], intercept=0.031091729334909588
epoch=11, coef=[0.04791486 0.22842062 0.023911  ], intercept=0.03335050795618497
epoch=12, coef=[0.05859816 0.21764833 0.01955045], intercept=0.03655207482707387
epoch=13, coef=[ 0.06385321  0.18533162 -0.00149716], intercept=0.03887655587501907
epoch=14, coef=[0.06737312 0.24241979 0.03878697], intercept=0.04123131324069443
epoch=15, coef=[0.01036241 0.20700097 0.00934672], intercept=0.04317350021857743
epoch=16, coef=[0.1189879  0.2035317  0.05180416], intercept=0.04611709595619019
epoch=17, coef=[0.04005371 0.20412041 0.02009224], intercept=0.04887168056302188
epoch=18, coef=[0.05961462 0.24953122 0.03024375], intercept=0.051774720130660354
epoch=19, coef=[0.04046754 0.22933655 0.01920213], intercept=0.05480784480968409
epoch=20, coef=[0.03825666 0.2300612  0.04988247], intercept=0.05756999290860441
epoch=21, coef=[0.05805849 0.19697941 0.00582342], intercept=0.06096834807726243
epoch=22, coef=[ 0.0077341   0.24557468 -0.04634925], intercept=0.06363741467067603
epoch=23, coef=[0.06688962 0.22542248 0.0075719 ], intercept=0.06670779666369407
epoch=24, coef=[ 0.04786459  0.20376878 -0.01105993], intercept=0.070073103362396
epoch=25, coef=[0.09021129 0.22811557 0.07462747], intercept=0.07233547697308551
epoch=26, coef=[0.03714964 0.19241255 0.03445639], intercept=0.07373289195318711
epoch=27, coef=[0.04468146 0.19691088 0.01938065], intercept=0.07557992254589425
epoch=28, coef=[0.07030201 0.21981199 0.02650136], intercept=0.07846012278833928
epoch=29, coef=[0.06054185 0.21269676 0.02769051], intercept=0.08182257276854596
epoch=30, coef=[0.05943493 0.23012164 0.02375801], intercept=0.08421539168099942
epoch=31, coef=[0.0070226  0.20668822 0.04714602], intercept=0.08667843224374469
epoch=32, coef=[ 0.07970519  0.19228484 -0.04536772], intercept=0.09045441288467675
epoch=33, coef=[0.05995577 0.21001972 0.02754392], intercept=0.09444695212055192
epoch=34, coef=[0.05996258 0.20199627 0.01251495], intercept=0.0963426862951923
epoch=35, coef=[0.03723968 0.18916539 0.01987454], intercept=0.09975512902267265
epoch=36, coef=[0.05279543 0.20344883 0.01068205], intercept=0.10362340766473248
epoch=37, coef=[1.61941626e-04 2.69098845e-01 6.88121261e-02], intercept=0.10436704028193486
epoch=38, coef=[0.04630599 0.24268833 0.00328241], intercept=0.10677416148659843
epoch=39, coef=[0.07744659 0.24709931 0.02757859], intercept=0.10900892861992696
epoch=40, coef=[0.06507881 0.19630759 0.0093369 ], intercept=0.11163613421017951
epoch=41, coef=[0.08834856 0.18705454 0.0281991 ], intercept=0.11433614982646066
epoch=42, coef=[ 0.01842144  0.22260337 -0.01856782], intercept=0.11864852923007295
epoch=43, coef=[0.0506988  0.23632025 0.00084075], intercept=0.12186418316544703
epoch=44, coef=[4.27150310e-05 2.22995840e-01 6.86881752e-03], intercept=0.12339210555203174
epoch=45, coef=[0.05204141 0.23501905 0.02778889], intercept=0.12614989479931987
epoch=46, coef=[0.05673432 0.24961824 0.00522061], intercept=0.1284616565497802
epoch=47, coef=[ 0.07025288  0.21266663 -0.01950665], intercept=0.13035553865886493
epoch=48, coef=[0.05691332 0.22546274 0.05282243], intercept=0.13257294289275784
epoch=49, coef=[0.05025129 0.21019069 0.04191554], intercept=0.13302652894862657
epoch=50, coef=[0.05548751 0.23209487 0.02706788], intercept=0.13801093443405324
epoch=51, coef=[0.06773041 0.24522297 0.02502841], intercept=0.1412367720256497
epoch=52, coef=[ 0.0436074   0.21310012 -0.00277106], intercept=0.14320569160754085
epoch=53, coef=[0.05927529 0.20839637 0.0493564 ], intercept=0.1455661402285461
epoch=54, coef=[0.05875666 0.22666579 0.00138491], intercept=0.1497331258380959
epoch=55, coef=[ 0.04575764  0.22609465 -0.0082161 ], intercept=0.1516129556697513
epoch=56, coef=[0.02411062 0.20251169 0.01184114], intercept=0.1528982868856327
epoch=57, coef=[6.24734358e-02 1.98538028e-01 1.78468893e-04], intercept=0.15484029943785593
epoch=58, coef=[0.06494535 0.17342336 0.01333073], intercept=0.15765077793158638
epoch=59, coef=[0.06176615 0.19415655 0.03729891], intercept=0.1601493037622657
epoch=60, coef=[0.07656987 0.22084761 0.01489296], intercept=0.16185024740479936
epoch=61, coef=[-0.03258327  0.18757787 -0.0171646 ], intercept=0.16593705705621065
epoch=62, coef=[ 0.07350844  0.20502539 -0.02901097], intercept=0.17147052514006178
epoch=63, coef=[0.04130138 0.20762439 0.00919844], intercept=0.17351666432195567
epoch=64, coef=[0.00681708 0.22874828 0.00666607], intercept=0.1757648174268554
epoch=65, coef=[ 0.06813993  0.20839807 -0.01201586], intercept=0.17826345754525716
epoch=66, coef=[-0.05422689  0.27368762 -0.01039931], intercept=0.1820957319192923
epoch=67, coef=[0.03934946 0.20223518 0.0240632 ], intercept=0.18086635972096424
epoch=68, coef=[0.12280498 0.21764286 0.01772129], intercept=0.1852739856264899
epoch=69, coef=[0.05186248 0.22122805 0.0119587 ], intercept=0.18743398339745637
epoch=70, coef=[0.07232394 0.21403475 0.0133196 ], intercept=0.18939918778719206
epoch=71, coef=[0.10691163 0.20905089 0.02745425], intercept=0.19185051044463192
epoch=72, coef=[0.06461815 0.18207562 0.00835372], intercept=0.19425719180919201
epoch=73, coef=[0.01663524 0.23247266 0.01772622], intercept=0.19674816198514736
epoch=74, coef=[ 0.04485534  0.19666025 -0.00931653], intercept=0.19934861778140706
epoch=75, coef=[ 0.08398967  0.17141105 -0.11956095], intercept=0.2013617141816913
epoch=76, coef=[0.03262934 0.25201598 0.00065251], intercept=0.2052676454546671
epoch=77, coef=[0.04876217 0.22337327 0.00961094], intercept=0.20787065179406863
epoch=78, coef=[0.06685888 0.20903441 0.03835924], intercept=0.21084588787609085
epoch=79, coef=[0.01830415 0.17235444 0.04894146], intercept=0.21234305684264382
epoch=80, coef=[0.05530249 0.16954538 0.03959677], intercept=0.21559339276798878
epoch=81, coef=[0.02542426 0.24566277 0.01317443], intercept=0.2176933849841378
epoch=82, coef=[0.05660152 0.22491037 0.02313947], intercept=0.2186757704354997
epoch=83, coef=[-0.03790122  0.24099957  0.03384729], intercept=0.22064346051978437
epoch=84, coef=[ 0.06615827  0.2336501  -0.00387232], intercept=0.22368099490078636
epoch=85, coef=[-0.0059149   0.19541596  0.04609641], intercept=0.22622065700744212
epoch=86, coef=[0.08617425 0.21117603 0.04176771], intercept=0.22919646717213032
epoch=87, coef=[0.04699879 0.21795819 0.07127757], intercept=0.23127535407067062
epoch=88, coef=[0.09656998 0.1983607  0.05898119], intercept=0.2339157980853713
epoch=89, coef=[0.05398585 0.20222824 0.01621565], intercept=0.23493769686331817

In [ ]:
y_pred = gd.predict(x_test)

In [ ]:
r2 = r2_score(y_test, y_pred)

In [ ]:
r2

0.8654905085336222

Our r2 score always change's because it takes only one random row not the whole dataset. whenever row change's score also changes.

got r2 0.8904600352844214 in batch gd

<h1> Scaled values

In [ ]:
from math import inf
x_scaled = (x - x.mean()) / x.std()
x_train,x_test,y_train,y_test = tts(x_scaled,y, test_size=0.2, random_state=42)



class SGDRegressor:

  def __init__(self,learning_rate=0.01,epochs=100, tolerance = 1e-17, patience = 15):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None
    self.tolerance = tolerance
    self.patience = patience

  def fit(self,x_train,y_train):

    # initializing random coef & intercept
    self.coef_ = np.ones(x_train.shape[1])
    self.intercept_ = 0

    previous_loss = float(inf)
    patience_counter = 0

    print(self.coef_,self.intercept_)

    for i in range(self.epochs):
      for j in range(x_train.shape[0]):

        idx = np.random.randint(0,x_train.shape[0])

        y_hat = np.dot(x_train.iloc[idx], self.coef_) + self.intercept_

        # Loss (MSE)
        loss = np.mean((y_train.iloc[idx] - y_hat) ** 2)

        intercept_der = -2 * (y_train.iloc[idx] - y_hat)
        self.intercept_ -= self.learning_rate * intercept_der

        coef_der = -2 * np.dot((y_train.iloc[idx] - y_hat), x_train.iloc[idx])
        self.coef_ -= self.learning_rate * coef_der

        # print control
      if i < 200 or i >= self.epochs - 200:
            print(f"epoch={i}, coef={self.coef_}, intercept={self.intercept_}")


        # early stopping
      if abs(previous_loss - loss) < self.tolerance:
        patience_counter +=1
        if patience_counter >= self.patience:
          print(f"Early stopping at epochs {i}")
          break
      else:
        patience_counter = 0
        previous_loss = loss

  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [ ]:
x_train.head(2)

           TV     Radio  Newspaper
79  -0.361572 -1.048306  -0.342262
197  0.348934 -0.940539  -1.109069

In [ ]:
gd = SGDRegressor(epochs=100,learning_rate=0.001)

In [ ]:
gd.fit(x_train,y_train)

[1. 1. 1.] 0
epoch=0, coef=[1.99170954 2.09704688 0.9609661 ], intercept=3.8594129079805235
epoch=1, coef=[2.7437972  2.04580636 0.61204859], intercept=6.638075516173456
epoch=2, coef=[2.98622654 2.10511127 0.54705284], intercept=8.686730090624494
epoch=3, coef=[3.3396795  2.2586462  0.52541885], intercept=10.193300645817061
epoch=4, coef=[3.58795458 2.42177043 0.39737575], intercept=11.254723959535214
epoch=5, coef=[3.66919505 2.43759423 0.25718988], intercept=12.061605085683377
epoch=6, coef=[3.76334962 2.57849584 0.29674045], intercept=12.629118302817433
epoch=7, coef=[3.77869007 2.63047969 0.20748411], intercept=13.02540868284302
epoch=8, coef=[3.85903222 2.64937645 0.21452195], intercept=13.241410935752542
epoch=9, coef=[3.89419727 2.68963678 0.21639512], intercept=13.473647534721168
epoch=10, coef=[3.89328217 2.60882016 0.22879265], intercept=13.603175035467979
epoch=11, coef=[3.88349813 2.63017043 0.23780758], intercept=13.78537966855387
epoch=12, coef=[3.95633057 2.68245636 0.28380779], intercept=13.800204504661929
epoch=13, coef=[3.91248822 2.7496634  0.25195546], intercept=13.888786958390112
epoch=14, coef=[3.91679528 2.71261571 0.28505548], intercept=13.900330154045228
epoch=15, coef=[3.93255661 2.72534904 0.24114422], intercept=13.881518477677904
epoch=16, coef=[3.8711073  2.78630755 0.23967244], intercept=13.917023012516918
epoch=17, coef=[3.94333849 2.74002447 0.19162058], intercept=13.961319123986263
epoch=18, coef=[3.87924279 2.69796615 0.17325064], intercept=13.954303545161185
epoch=19, coef=[3.94078997 2.68271211 0.13619913], intercept=13.946438344779388
epoch=20, coef=[3.94955387 2.73227647 0.07812663], intercept=14.00060703999542
epoch=21, coef=[3.88660847 2.74351023 0.0794971 ], intercept=13.970875049095385
epoch=22, coef=[3.89423567 2.76254243 0.03357172], intercept=13.976245796674744
epoch=23, coef=[3.83552699 2.74785772 0.07132796], intercept=14.01746872554906
epoch=24, coef=[3.85854666 2.78195575 0.08917343], intercept=14.056604496195108
epoch=25, coef=[3.84017353 2.7441127  0.08302178], intercept=14.023735603853087
epoch=26, coef=[3.78640461 2.77459083 0.03651885], intercept=14.063820450216365
epoch=27, coef=[3.67802936 2.83895802 0.03723835], intercept=14.069508723667008
epoch=28, coef=[3.65613005 2.85560114 0.06226918], intercept=14.070976331638347
epoch=29, coef=[3.65596841 2.87448117 0.07842418], intercept=14.087629113416197
epoch=30, coef=[3.70059201 2.86500375 0.08473703], intercept=14.053381768371422
epoch=31, coef=[3.72605238 2.90801905 0.08073016], intercept=13.98801504440653
epoch=32, coef=[3.71305485 2.89168333 0.07499479], intercept=14.021741980611578
epoch=33, coef=[ 3.78211579  2.82409162 -0.01668115], intercept=14.002076935650623
epoch=34, coef=[ 3.81533888  2.81777869 -0.01558305], intercept=14.041202412351856
epoch=35, coef=[ 3.89742118  2.77289238 -0.04474986], intercept=13.992805716393262
epoch=36, coef=[ 3.97294975  2.77276364 -0.02430236], intercept=14.081607790750292
epoch=37, coef=[ 3.87843560e+00  2.84814498e+00 -2.99284536e-03], intercept=14.078131615749456
epoch=38, coef=[ 3.85189574  2.90348899 -0.03442066], intercept=14.115231117631549
epoch=39, coef=[3.78220646 2.94418625 0.09962365], intercept=14.069501793639992
epoch=40, coef=[ 3.83268153  2.81477433 -0.01756124], intercept=14.059778348893786
epoch=41, coef=[ 3.89699504  2.66607691 -0.03773528], intercept=13.997550123045274
epoch=42, coef=[3.79535473 2.74256199 0.06530916], intercept=14.03965467765142
epoch=43, coef=[3.77669048 2.7280482  0.03185369], intercept=14.041880477369558
epoch=44, coef=[3.89778136 2.72468455 0.03578569], intercept=14.045271723511316
epoch=45, coef=[3.868635   2.77538329 0.06061174], intercept=14.038291050123743
epoch=46, coef=[3.86214881e+00 2.73103234e+00 1.65620879e-06], intercept=14.032309815747048
epoch=47, coef=[ 3.89294398  2.75698826 -0.09322917], intercept=14.05246341398721
epoch=48, coef=[ 3.84566072  2.81074748 -0.07034972], intercept=14.073664290215268
epoch=49, coef=[ 3.82976217  2.85765375 -0.0407302 ], intercept=14.007963176037192
epoch=50, coef=[3.80588656 2.84211479 0.01823391], intercept=13.988181765003421
epoch=51, coef=[3.90351626 2.82007504 0.18504763], intercept=13.930931012151184
epoch=52, coef=[3.8723128  2.84519335 0.17882881], intercept=13.931361277958388
epoch=53, coef=[3.78990186 2.85913529 0.10640547], intercept=13.981031594549199
epoch=54, coef=[3.75030582 2.80969563 0.0847744 ], intercept=14.048299097002772
epoch=55, coef=[3.79733601 2.78925875 0.08198281], intercept=14.046466572989381
epoch=56, coef=[3.73741974 2.77801565 0.09056636], intercept=14.00374599241585
epoch=57, coef=[3.80798124 2.74983495 0.05279529], intercept=13.974131243483956
epoch=58, coef=[3.8207164  2.81061251 0.11110423], intercept=14.009387179696033
epoch=59, coef=[3.75910382 2.86845235 0.08813115], intercept=14.067564300211611
epoch=60, coef=[3.7348721  2.81925861 0.04227737], intercept=14.046013104250358
epoch=61, coef=[3.77165655 2.84522633 0.0190178 ], intercept=14.07812281611107
epoch=62, coef=[3.74247957 2.81634921 0.04477348], intercept=14.126775887999736
epoch=63, coef=[3.81291899 2.75225502 0.06513439], intercept=14.070043392651518
epoch=64, coef=[3.82793091 2.82369464 0.06596269], intercept=14.053958489393807
epoch=65, coef=[3.75017723 2.84185836 0.10283841], intercept=14.037195182952745
epoch=66, coef=[3.69226329 2.88978112 0.10344685], intercept=14.085828567019501
epoch=67, coef=[3.77457826 2.84852776 0.08712914], intercept=14.072832519106067
epoch=68, coef=[3.73668814 2.86400457 0.09894119], intercept=14.083866946442617
epoch=69, coef=[3.77364772 2.8736648  0.05058891], intercept=14.09446171645553
epoch=70, coef=[3.72320296 2.86206164 0.08346379], intercept=14.138466617487266
epoch=71, coef=[3.81084448 2.80071932 0.14147286], intercept=14.065600994504162
epoch=72, coef=[3.70725774 2.85158763 0.124477  ], intercept=14.097703279080667
epoch=73, coef=[3.75955119 2.85852178 0.18749866], intercept=14.12007269011072
epoch=74, coef=[3.80569661 2.86235309 0.18504018], intercept=14.100767330303082
epoch=75, coef=[3.83274701 2.78260778 0.14140651], intercept=14.072021721735103
epoch=76, coef=[3.88777314 2.7603319  0.08506768], intercept=14.065964555450426
epoch=77, coef=[3.82404652 2.82595503 0.08200948], intercept=14.038949862412272
epoch=78, coef=[3.86844193 2.78125701 0.17060347], intercept=14.002848667491145
epoch=79, coef=[3.86507692 2.78538895 0.14702295], intercept=14.03435935374761
epoch=80, coef=[3.86668421 2.79528993 0.09626141], intercept=14.027719083836852
epoch=81, coef=[3.91834444 2.73146438 0.07124713], intercept=14.067733390357791
epoch=82, coef=[3.92045714 2.72631767 0.1013084 ], intercept=14.016955401422663
epoch=83, coef=[3.97762569 2.69565302 0.1227296 ], intercept=13.961795394464005
epoch=84, coef=[3.86509926 2.75201994 0.11157434], intercept=13.987899247516241
epoch=85, coef=[3.82280845 2.73518664 0.1119908 ], intercept=13.972382869496638
epoch=86, coef=[3.77707578 2.77363223 0.09565117], intercept=14.001528387603813
epoch=87, coef=[3.89178267 2.67478788 0.09966485], intercept=13.960506070567714
epoch=88, coef=[3.84899811 2.72068042 0.11468353], intercept=14.007328391753257
epoch=89, coef=[3.93769581 2.65172776 0.0957094 ], intercept=14.020549711023696
epoch=90, coef=[3.9764159  2.63736583 0.07890463], intercept=14.065626969767363
epoch=91, coef=[3.99473258 2.65309176 0.0606716 ], intercept=14.075038393497849
epoch=92, coef=[4.02469326 2.67935186 0.06404182], intercept=14.098576815238383
epoch=93, coef=[3.96904061 2.71569842 0.12556708], intercept=14.059782037946484
epoch=94, coef=[3.92619295 2.78823635 0.16474906], intercept=14.046645349150147
epoch=95, coef=[3.94848374 2.81915572 0.2022149 ], intercept=14.074976680686783
epoch=96, coef=[3.87778369 2.80912209 0.15677804], intercept=14.062359913945333
epoch=97, coef=[3.87795689 2.76411345 0.16711742], intercept=14.039895910500094
epoch=98, coef=[3.84393747 2.8052741  0.08778417], intercept=13.993501837669642
epoch=99, coef=[3.90972051 2.78511655 0.16354476], intercept=14.011087294543412

In [ ]:
y_pred = gd.predict(x_test)

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

0.898298971651692

In [ ]:
sk_pred = 0.899438024100912
gd_pred = r2

if gd_pred > sk_pred:
  diff_gd = gd_pred - sk_pred
  print("GD working better:",diff_gd)
elif gd_pred < sk_pred:
  diff_sk = sk_pred - gd_pred
  print("sklearn model working better with",diff_sk)
else:
  print("No difference both got same score")

sklearn model working better with 0.0011390524492199683

To control this learning rate we apply learning shedule functions. These functions decrease learning rate over the iteration so we will not deviate from the actual minima.