In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts

In [ ]:
df = pd.read_csv("Advertising.csv")
df.head(3)

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3

In [ ]:
df = df.drop("Unnamed: 0", axis=1)

In [ ]:
df.head(2)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4

In [ ]:
x = df.drop("Sales", axis=1)
y = df['Sales']

print(x.shape)
print(y.shape)

(200, 3)
(200,)

In [ ]:
x_train,x_test,y_train,y_test = tts(x,y, test_size=0.2, random_state=42)

In [ ]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
print("coeff:",lr.coef_)
print("intercept:",lr.intercept_)

coeff: [0.04472952 0.18919505 0.00276111]
intercept: 2.979067338122629

In [ ]:
y_pred = lr.predict(x_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
print(r2)

0.899438024100912

<h1> Using Class

In [ ]:
x_train.shape

(160, 3)

coeff: [0.04472952 0.18919505 0.00276111]
intercept: 2.979067338122629

In [ ]:
class GDRegressor:

  def __init__(self,learning_rate=0.01,epochs=100):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None

  def fit(self,x_train,y_train):

    # initializing random coef & intercept
    self.coef_ = np.ones(x_train.shape[1])
    self.intercept_ = 0

    print(self.coef_,self.intercept_)

    for i in range(self.epochs):

        y_hat = np.dot(x_train, self.coef_) + self.intercept_

        intercept_der = -2 * np.mean(y_train - y_hat)
        self.intercept_ -= self.learning_rate * intercept_der

        coef_der = -2 * np.dot((y_train - y_hat), x_train) / x_train.shape[0]
        self.coef_ -= self.learning_rate * coef_der

        # print control
        if i < 200 or i >= self.epochs - 200:
            print(f"epoch={i}, coef={self.coef_}, intercept={self.intercept_}")


  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [ ]:
gd = GDRegressor(epochs=90000,learning_rate=0.00003)

In [ ]:
gd.fit(x_train,y_train)

[1. 1. 1.] 0
epoch=0, coef=[-1.11000196  0.71956697  0.62877668], intercept=-0.0113244375
epoch=1, coef=[0.68557469 0.91239919 0.87304452], intercept=-0.00260382932026167
epoch=2, coef=[-0.81335674  0.70797238  0.60136423], intercept=-0.010749576220267175
epoch=3, coef=[0.46546611 0.84036473 0.76780039], intercept=-0.004633987341707923
epoch=4, coef=[-0.59899984  0.69040839  0.56760341], intercept=-0.01051041325073479
epoch=5, coef=[0.31213281 0.78020606 0.67933472], intercept=-0.006239533416515967
epoch=6, coef=[-0.44346389  0.6693674   0.53060352], intercept=-0.010494165441627148
epoch=7, coef=[0.20601287 0.7292288  0.6040215 ], intercept=-0.007527932334199647
epoch=8, coef=[-0.3300321   0.64655581  0.4924638 ], intercept=-0.010621997944943926
epoch=9, coef=[0.13321743 0.68545324 0.5391745 ], intercept=-0.008576938329001287
epoch=10, coef=[-0.24679127  0.6231267   0.45457492], intercept=-0.010839100724692005
epoch=11, coef=[0.08389043 0.64741344 0.4827853 ], intercept=-0.009443058626034005
epoch=12, coef=[-0.18524679  0.59984496  0.41783251], intercept=-0.011107641070466846
epoch=13, coef=[0.05104219 0.61401395 0.43333616], intercept=-0.010167583222555855
epoch=14, coef=[-0.13933738  0.57720414  0.38278836], intercept=-0.01140176073689252
epoch=15, coef=[0.02971996 0.58442743 0.38966618], intercept=-0.01078088277492952
epoch=16, coef=[-0.10473418  0.55550924  0.34975712], intercept=-0.011704026474416575
epoch=17, coef=[0.01641807 0.55802144 0.35087533], intercept=-0.01130547387262119
epoch=18, coef=[-0.07834205  0.53493513  0.31889162], intercept=-0.012002913511065907
epoch=19, coef=[0.00865867 0.53430598 0.31625572], intercept=-0.011758206882671937
epoch=20, coef=[-0.05794477  0.51556782  0.29023584], intercept=-0.012291023015255682
epoch=21, coef=[0.00469353 0.51289587 0.285242  ], intercept=-0.012151829052548737
epoch=22, coef=[-0.04195253  0.49743345  0.26376195], intercept=-0.012563820959470524
epoch=23, coef=[0.00329213 0.49348369 0.25737565], intercept=-0.012496102653913254
epoch=24, coef=[-0.02922224  0.48051862  0.2393963 ], intercept=-0.012818747243764268
epoch=25, coef=[0.00359107 0.47582021 0.23227909], intercept=-0.01279860609090876
epoch=26, coef=[-0.01892964  0.46478459  0.21703734], intercept=-0.013054587631560668
epoch=27, coef=[0.00498701 0.45970027 0.20963679], intercept=-0.013065309007308753
epoch=28, coef=[-0.01047818  0.45017716  0.19656798], intercept=-0.013271032122689265
epoch=29, coef=[0.00706063 0.44495247 0.18918151], intercept=-0.013300986185179364
epoch=30, coef=[-0.0034342   0.43663343  0.17786404], intercept=-0.01346836548471471
epoch=31, coef=[0.00952266 0.43143164 0.17068409], intercept=-0.01350951635944986
epoch=32, coef=[0.0025193  0.42408642 0.16079985], intercept=-0.013647251375706031
epoch=33, coef=[0.01217551 0.41901329 0.15394589], intercept=-0.013694098791458938
epoch=34, coef=[0.00761558 0.41246822 0.145252  ], intercept=-0.01380858266337488
epoch=35, coef=[0.01488611 0.40758947 0.1387931 ], intercept=-0.01385741099497364
epoch=36, coef=[0.01202767 0.40171196 0.13110165], intercept=-0.013953378488309694
epoch=37, coef=[0.01756664 0.3970657  0.12507245], intercept=-0.014001724284220083
epoch=38, coef=[0.01588516 0.39175318 0.11823593], intercept=-0.014082714265494237
epoch=39, coef=[0.02016081 0.3873586  0.11264786], intercept=-0.014128989028354258
epoch=40, coef=[0.01928612 0.38253055 0.10654873], intercept=-0.014197674831744101
epoch=41, coef=[0.02263428 0.37839408 0.10139784], intercept=-0.014240898090928083
epoch=42, coef=[0.02230574 0.37398635 0.095941  ], intercept=-0.014299323798887244
epoch=43, coef=[0.02496778 0.37010596 0.09121349], intercept=-0.014338934508229333
epoch=44, coef=[0.02500243 0.3660666  0.08632078], intercept=-0.014388684198975097
epoch=45, coef=[0.02715233 0.36243484 0.08199681], intercept=-0.014424407733768947
epoch=46, coef=[0.02742224 0.35872116 0.07760306], intercept=-0.014466726947159841
epoch=47, coef=[0.02918585 0.35532721 0.07365936], intercept=-0.014498481546266276
epoch=48, coef=[0.02960204 0.35190357 0.06970949], intercept=-0.01453436466981286
epoch=49, coef=[0.03107079 0.34873472 0.06612117], intercept=-0.014562195841988297
epoch=50, coef=[0.0315718  0.34557098 0.06256801], intercept=-0.014592449170674116
epoch=51, coef=[0.03281247 0.34261358 0.05930975], intercept=-0.014616483907329792
epoch=52, coef=[0.03335627 0.33968389 0.0561125 ], intercept=-0.014641771322135422
epoch=53, coef=[0.03441796 0.33692405 0.05315935], intercept=-0.014662186321586109
epoch=54, coef=[0.03497618 0.33420604 0.05028237], intercept=-0.014683062533201431
epoch=55, coef=[0.03589526 0.33163002 0.04761025], intercept=-0.014700062321397225
epoch=56, coef=[0.03644911 0.32910409 0.04502213], intercept=-0.014716997203635746
epoch=57, coef=[0.03725281 0.32669864 0.04260815], intercept=-0.014730799230640171
epoch=58, coef=[0.0377902  0.3243475  0.04028104], intercept=-0.014744195756140563
epoch=59, coef=[0.03849906 0.32209998 0.03810365], intercept=-0.014755020396510159
epoch=60, coef=[0.03901256 0.31990826 0.03601271], intercept=-0.014765227967071881
epoch=61, coef=[0.03964233 0.31780674 0.03405179], intercept=-0.014773291955581748
epoch=62, coef=[0.04012771 0.31576073 0.03217478], intercept=-0.014780616406751938
epoch=63, coef=[0.04069058 0.31379404 0.03041163], intercept=-0.014786128669558805
epoch=64, coef=[0.0411458  0.31188141 0.02872854], intercept=-0.014790839863988261
epoch=65, coef=[0.04165139 0.31003917 0.02714587], intercept=-0.014793999009794554
epoch=66, coef=[0.04207587 0.3082488  0.02563868], intercept=-0.014796336673820064
epoch=67, coef=[0.04253184 0.30652139 0.02422056], intercept=-0.014797329625790135
epoch=68, coef=[0.04292599 0.30484324 0.02287296], intercept=-0.014797507898381993
epoch=69, coef=[0.04333857 0.30322174 0.02160474], intercept=-0.014796509300989663
epoch=70, coef=[0.0437034  0.3016467  0.02040196], intercept=-0.014794720332075791
epoch=71, coef=[0.04407774 0.30012293 0.01927021], intercept=-0.01479189247588185
epoch=72, coef=[0.04441465 0.29864273 0.01819887], intercept=-0.014788309316792451
epoch=73, coef=[0.04475501 0.29720912 0.01719127], intercept=-0.014783802401269407
epoch=74, coef=[0.04506561 0.29581623 0.01623922], intercept=-0.014778581362732043
epoch=75, coef=[0.04537564 0.29446584 0.01534449], intercept=-0.014772533971849267
epoch=76, coef=[0.04566162 0.29315341 0.01450069], intercept=-0.014765816576843999
epoch=77, coef=[0.04594445 0.29187986 0.01370852], intercept=-0.014758356280725292
epoch=78, coef=[0.04620753 0.29064163 0.01296293], intercept=-0.014750270905062259
epoch=79, coef=[0.04646586 0.28943907 0.01226392], intercept=-0.014741514928269254
epoch=80, coef=[0.04670773 0.28826935 0.01160741], intercept=-0.01473217819704794
epoch=81, coef=[0.04694392 0.2871324  0.01099296], intercept=-0.014722234113224679
epoch=82, coef=[0.04716622 0.28602596 0.01041722], intercept=-0.014711752103579395
epoch=83, coef=[0.04738236 0.28494971 0.00987947], intercept=-0.014700718529660073
epoch=84, coef=[0.04758662 0.28390177 0.00937695], intercept=-0.014689187817399446
epoch=85, coef=[0.04778458 0.2828817  0.00890875], intercept=-0.014677155089998343
epoch=86, coef=[0.04797225 0.28188792 0.00847256], intercept=-0.014664663668491259
epoch=87, coef=[0.04815369 0.28091989 0.00806738], intercept=-0.014651714491644771
epoch=88, coef=[0.04832612 0.27997627 0.00769124], intercept=-0.01463834258458185
epoch=89, coef=[0.04849252 0.27905647 0.00734314], intercept=-0.014624552642537784
epoch=90, coef=[0.04865099 0.27815936 0.00702136], intercept=-0.0146103734272875
epoch=91, coef=[0.0488037  0.27728432 0.0067249 ], intercept=-0.014595811959132959
epoch=92, coef=[0.04894935 0.27643037 0.00645228], intercept=-0.01458089221380238
epoch=93, coef=[0.04908957 0.2755969  0.00620252], intercept=-0.014565622548812107
epoch=94, coef=[0.0492235  0.27478304 0.00597433], intercept=-0.014550023233448596
epoch=95, coef=[0.04935233 0.2739882  0.00576677], intercept=-0.014534103287420629
epoch=96, coef=[0.04947552 0.27321161 0.0055787 ], intercept=-0.014517880067791918
epoch=97, coef=[0.04959395 0.27245272 0.00540925], intercept=-0.014501362801529513
epoch=98, coef=[0.0497073  0.27171084 0.00525738], intercept=-0.01448456652240905
epoch=99, coef=[0.04981624 0.27098542 0.00512228], intercept=-0.014467500364057551
epoch=100, coef=[0.04992059 0.27027587 0.00500305], intercept=-0.014450177477786602
epoch=101, coef=[0.05002086 0.26958167 0.00489892], intercept=-0.014432606711047484
epoch=102, coef=[0.05011696 0.26890227 0.00480907], intercept=-0.014414799666249773
epoch=103, coef=[0.05020931 0.2682372  0.00473281], intercept=-0.014396764786646496
epoch=104, coef=[0.05029787 0.26758596 0.00466939], intercept=-0.01437851238126667
epoch=105, coef=[0.05038298 0.26694811 0.00461818], intercept=-0.014360050422680907
epoch=106, coef=[0.05046463 0.2663232  0.0045785 ], intercept=-0.014341388124955405
epoch=107, coef=[0.05054311 0.26571081 0.00454978], intercept=-0.01432253295862471
epoch=108, coef=[0.05061845 0.26511054 0.0045314 ], intercept=-0.014303493199137294
epoch=109, coef=[0.05069087 0.264522   0.00452283], intercept=-0.014284275807231989
epoch=110, coef=[0.05076043 0.26394481 0.00452353], intercept=-0.014264888244830349
epoch=111, coef=[0.05082731 0.26337863 0.004533  ], intercept=-0.014245336970626356
epoch=112, coef=[0.05089157 0.2628231  0.00455075], intercept=-0.014225628734662113
epoch=113, coef=[0.05095337 0.26227791 0.00457632], intercept=-0.014205769511209944
epoch=114, coef=[0.05101278 0.26174273 0.00460928], intercept=-0.014185765422298316
epoch=115, coef=[0.05106994 0.26121726 0.00464922], intercept=-0.01416562198136471
epoch=116, coef=[0.05112491 0.26070121 0.00469572], intercept=-0.014145344752631914
epoch=117, coef=[0.05117781 0.26019431 0.00474842], intercept=-0.014124938815565518
epoch=118, coef=[0.05122872 0.25969628 0.00480695], intercept=-0.014104409236154185
epoch=119, coef=[0.05127772 0.25920687 0.00487097], intercept=-0.014083760688203686
epoch=120, coef=[0.0513249  0.25872583 0.00494015], intercept=-0.014062997790633398
epoch=121, coef=[0.05137034 0.25825292 0.00501418], intercept=-0.014042124840128102
epoch=122, coef=[0.0514141  0.25778792 0.00509276], intercept=-0.014021146052955494
epoch=123, coef=[0.05145626 0.2573306  0.00517561], intercept=-0.014000065376645858
epoch=124, coef=[0.05149689 0.25688075 0.00526245], intercept=-0.013978886663733071
epoch=125, coef=[0.05153606 0.25643818 0.00535303], intercept=-0.013957613539482907
epoch=126, coef=[0.05157382 0.25600268 0.00544711], intercept=-0.013936249527062117
epoch=127, coef=[0.05161023 0.25557407 0.00554445], intercept=-0.013914797954985398
epoch=128, coef=[0.05164535 0.25515216 0.00564483], intercept=-0.013893262047598514
epoch=129, coef=[0.05167924 0.25473679 0.00574804], intercept=-0.013871644860642013
epoch=130, coef=[0.05171195 0.25432778 0.00585388], intercept=-0.013849949346936933
epoch=131, coef=[0.05174352 0.25392498 0.00596216], intercept=-0.013828178311825071
epoch=132, coef=[0.05177401 0.25352822 0.00607269], intercept=-0.013806334461101593
epoch=133, coef=[0.05180346 0.25313737 0.0061853 ], intercept=-0.013784420370481667
epoch=134, coef=[0.0518319  0.25275227 0.00629983], intercept=-0.013762438520800366
epoch=135, coef=[0.0518594  0.25237279 0.00641612], intercept=-0.013740391277354413
epoch=136, coef=[0.05188597 0.25199879 0.00653403], intercept=-0.013718280915949383
epoch=137, coef=[0.05191167 0.25163015 0.0066534 ], intercept=-0.013696109609172839
epoch=138, coef=[0.05193652 0.25126673 0.00677411], intercept=-0.013673879445843548
epoch=139, coef=[0.05196057 0.25090843 0.00689603], intercept=-0.013651592422130349
epoch=140, coef=[0.05198384 0.25055511 0.00701904], intercept=-0.01362925045622814
epoch=141, coef=[0.05200637 0.25020668 0.00714303], intercept=-0.013606855382846417
epoch=142, coef=[0.05202819 0.24986303 0.00726787], intercept=-0.01358440896441691
epoch=143, coef=[0.05204932 0.24952404 0.00739348], intercept=-0.013561912887908673
epoch=144, coef=[0.05206979 0.24918963 0.00751975], intercept=-0.013539368773501877
epoch=145, coef=[0.05208963 0.24885968 0.00764658], intercept=-0.01351677817299367
epoch=146, coef=[0.05210887 0.24853412 0.0077739 ], intercept=-0.013494142576608645
epoch=147, coef=[0.05212753 0.24821284 0.00790161], intercept=-0.013471463412477734
epoch=148, coef=[0.05214563 0.24789576 0.00802964], intercept=-0.013448742052067603
epoch=149, coef=[0.0521632  0.24758279 0.00815791], intercept=-0.013425979810369451
epoch=150, coef=[0.05218025 0.24727386 0.00828634], intercept=-0.013403177950295211
epoch=151, coef=[0.0521968  0.24696888 0.00841488], intercept=-0.013380337683322628
epoch=152, coef=[0.05221289 0.24666778 0.00854346], intercept=-0.013357460173110142
epoch=153, coef=[0.05222851 0.24637048 0.00867202], intercept=-0.01333454653642211
epoch=154, coef=[0.0522437  0.24607691 0.00880049], intercept=-0.013311597846145584
epoch=155, coef=[0.05225846 0.24578699 0.00892884], intercept=-0.013288615132374264
epoch=156, coef=[0.05227283 0.24550067 0.00905699], intercept=-0.013265599384961187
epoch=157, coef=[0.0522868  0.24521787 0.00918492], intercept=-0.01324255155467862
epoch=158, coef=[0.05230039 0.24493854 0.00931256], intercept=-0.013219472555405332
epoch=159, coef=[0.05231363 0.2446626  0.00943989], intercept=-0.01319636326530677
epoch=160, coef=[0.05232651 0.24439001 0.00956685], intercept=-0.013173224528730201
epoch=161, coef=[0.05233907 0.24412069 0.00969342], intercept=-0.013150057157368517
epoch=162, coef=[0.0523513  0.2438546  0.00981955], intercept=-0.013126861931918189
epoch=163, coef=[0.05236322 0.24359168 0.00994521], intercept=-0.013103639603203324
epoch=164, coef=[0.05237485 0.24333188 0.01007037], intercept=-0.013080390893638074
epoch=165, coef=[0.05238618 0.24307514 0.010195  ], intercept=-0.013057116498296772
epoch=166, coef=[0.05239724 0.24282142 0.01031907], intercept=-0.013033817086212755
epoch=167, coef=[0.05240803 0.24257066 0.01044256], intercept=-0.013010493301386743
epoch=168, coef=[0.05241857 0.24232281 0.01056544], intercept=-0.012987145763946948
epoch=169, coef=[0.05242886 0.24207784 0.01068769], intercept=-0.012963775071092155
epoch=170, coef=[0.05243891 0.24183569 0.01080929], intercept=-0.012940381798132767
epoch=171, coef=[0.05244872 0.24159633 0.01093022], intercept=-0.01291696649936795
epoch=172, coef=[0.05245832 0.2413597  0.01105045], intercept=-0.012893529709023337
epoch=173, coef=[0.0524677  0.24112577 0.01116998], intercept=-0.01287007194206349
epoch=174, coef=[0.05247687 0.24089449 0.01128879], intercept=-0.01284659369503911
epoch=175, coef=[0.05248584 0.24066583 0.01140686], intercept=-0.012823095446837223
epoch=176, coef=[0.05249462 0.24043975 0.01152418], intercept=-0.012799577659448518
epoch=177, coef=[0.05250321 0.2402162  0.01164074], intercept=-0.01277604077865841
epoch=178, coef=[0.05251162 0.23999516 0.01175652], intercept=-0.012752485234743384
epoch=179, coef=[0.05251986 0.23977658 0.01187151], intercept=-0.012728911443106486
epoch=180, coef=[0.05252792 0.23956044 0.01198571], intercept=-0.012705319804910239
epoch=181, coef=[0.05253582 0.23934669 0.01209911], intercept=-0.012681710707660235
epoch=182, coef=[0.05254357 0.2391353  0.0122117 ], intercept=-0.012658084525781143
epoch=183, coef=[0.05255116 0.23892624 0.01232347], intercept=-0.012634441621152109
epoch=184, coef=[0.0525586  0.23871948 0.01243441], intercept=-0.0126107823436315
epoch=185, coef=[0.0525659  0.23851499 0.01254453], intercept=-0.012587107031547737
epoch=186, coef=[0.05257306 0.23831273 0.01265381], intercept=-0.012563416012177739
epoch=187, coef=[0.05258009 0.23811268 0.01276225], intercept=-0.012539709602196648
epoch=188, coef=[0.05258698 0.2379148  0.01286985], intercept=-0.012515988108114363
epoch=189, coef=[0.05259375 0.23771907 0.01297661], intercept=-0.012492251826687447
epoch=190, coef=[0.05260039 0.23752546 0.01308251], intercept=-0.012468501045317645
epoch=191, coef=[0.05260692 0.23733394 0.01318757], intercept=-0.012444736042429062
epoch=192, coef=[0.05261332 0.23714449 0.01329177], intercept=-0.012420957087832153
epoch=193, coef=[0.05261962 0.23695707 0.01339513], intercept=-0.01239716444306904
epoch=194, coef=[0.05262581 0.23677166 0.01349763], intercept=-0.012373358361746111
epoch=195, coef=[0.05263189 0.23658824 0.01359927], intercept=-0.012349539089850146
epoch=196, coef=[0.05263787 0.23640678 0.01370007], intercept=-0.012325706866052338
epoch=197, coef=[0.05264374 0.23622726 0.01380001], intercept=-0.012301861921997692
epoch=198, coef=[0.05264953 0.23604965 0.0138991 ], intercept=-0.012278004482583031
epoch=199, coef=[0.05265521 0.23587393 0.01399734], intercept=-0.012254134766221928
epoch=89800, coef=[0.04872015 0.20329594 0.01280778], intercept=1.5601215836652742
epoch=89801, coef=[0.04872012 0.20329583 0.0128077 ], intercept=1.560133394836315
epoch=89802, coef=[0.04872009 0.20329571 0.01280762], intercept=1.5601452059090406
epoch=89803, coef=[0.04872005 0.20329559 0.01280753], intercept=1.560157016883452
epoch=89804, coef=[0.04872002 0.20329547 0.01280745], intercept=1.56016882775955
epoch=89805, coef=[0.04871999 0.20329536 0.01280736], intercept=1.5601806385373354
epoch=89806, coef=[0.04871995 0.20329524 0.01280728], intercept=1.5601924492168089
epoch=89807, coef=[0.04871992 0.20329512 0.0128072 ], intercept=1.5602042597979715
epoch=89808, coef=[0.04871989 0.20329501 0.01280711], intercept=1.5602160702808239
epoch=89809, coef=[0.04871985 0.20329489 0.01280703], intercept=1.5602278806653669
epoch=89810, coef=[0.04871982 0.20329477 0.01280695], intercept=1.5602396909516014
epoch=89811, coef=[0.04871979 0.20329465 0.01280686], intercept=1.5602515011395282
epoch=89812, coef=[0.04871975 0.20329454 0.01280678], intercept=1.560263311229148
epoch=89813, coef=[0.04871972 0.20329442 0.0128067 ], intercept=1.5602751212204617
epoch=89814, coef=[0.04871969 0.2032943  0.01280661], intercept=1.5602869311134704
epoch=89815, coef=[0.04871965 0.20329418 0.01280653], intercept=1.5602987409081746
epoch=89816, coef=[0.04871962 0.20329407 0.01280645], intercept=1.5603105506045751
epoch=89817, coef=[0.04871959 0.20329395 0.01280636], intercept=1.5603223602026728
epoch=89818, coef=[0.04871955 0.20329383 0.01280628], intercept=1.5603341697024684
epoch=89819, coef=[0.04871952 0.20329371 0.01280619], intercept=1.5603459791039629
epoch=89820, coef=[0.04871949 0.2032936  0.01280611], intercept=1.560357788407157
epoch=89821, coef=[0.04871945 0.20329348 0.01280603], intercept=1.5603695976120517
epoch=89822, coef=[0.04871942 0.20329336 0.01280594], intercept=1.5603814067186477
epoch=89823, coef=[0.04871939 0.20329325 0.01280586], intercept=1.5603932157269458
epoch=89824, coef=[0.04871935 0.20329313 0.01280578], intercept=1.5604050246369467
epoch=89825, coef=[0.04871932 0.20329301 0.01280569], intercept=1.5604168334486515
epoch=89826, coef=[0.04871929 0.20329289 0.01280561], intercept=1.5604286421620608
epoch=89827, coef=[0.04871925 0.20329278 0.01280553], intercept=1.5604404507771754
epoch=89828, coef=[0.04871922 0.20329266 0.01280544], intercept=1.5604522592939962
epoch=89829, coef=[0.04871919 0.20329254 0.01280536], intercept=1.560464067712524
epoch=89830, coef=[0.04871916 0.20329242 0.01280527], intercept=1.5604758760327597
epoch=89831, coef=[0.04871912 0.20329231 0.01280519], intercept=1.5604876842547042
epoch=89832, coef=[0.04871909 0.20329219 0.01280511], intercept=1.560499492378358
epoch=89833, coef=[0.04871906 0.20329207 0.01280502], intercept=1.560511300403722
epoch=89834, coef=[0.04871902 0.20329195 0.01280494], intercept=1.5605231083307973
epoch=89835, coef=[0.04871899 0.20329184 0.01280486], intercept=1.5605349161595845
epoch=89836, coef=[0.04871896 0.20329172 0.01280477], intercept=1.5605467238900843
epoch=89837, coef=[0.04871892 0.2032916  0.01280469], intercept=1.5605585315222978
epoch=89838, coef=[0.04871889 0.20329148 0.01280461], intercept=1.5605703390562258

In [ ]:
y_pred = gd.predict(x_test)

In [ ]:
r2 = r2_score(y_test, y_pred)

In [ ]:
r2

0.8904600352844214

<h1> Scaled values

In [ ]:
from math import inf
x_scaled = (x - x.mean()) / x.std()
x_train,x_test,y_train,y_test = tts(x_scaled,y, test_size=0.2, random_state=42)



class GDRegressor:

  def __init__(self,learning_rate=0.01,epochs=100, tolerance = 1e-17, patience = 15):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None
    self.tolerance = tolerance
    self.patience = patience

  def fit(self,x_train,y_train):

    # initializing random coef & intercept
    self.coef_ = np.ones(x_train.shape[1])
    self.intercept_ = 0

    previous_loss = float(inf)
    patience_counter = 0

    print(self.coef_,self.intercept_)

    for i in range(self.epochs):

        y_hat = np.dot(x_train, self.coef_) + self.intercept_

        # Loss (MSE)
        loss = np.mean((y_train - y_hat) ** 2)

        intercept_der = -2 * np.mean(y_train - y_hat)
        self.intercept_ -= self.learning_rate * intercept_der

        coef_der = -2 * np.dot((y_train - y_hat), x_train) / x_train.shape[0]
        self.coef_ -= self.learning_rate * coef_der

        # print control
        if i < 200 or i >= self.epochs - 200:
            print(f"epoch={i}, coef={self.coef_}, intercept={self.intercept_}")


        # early stopping
        if abs(previous_loss - loss) < self.tolerance:
          patience_counter +=1
          if patience_counter >= self.patience:
            print(f"Early stopping at epochs {i}")
            break
        else:
          patience_counter = 0
        previous_loss = loss

  def predict(self,x_test):
    return np.dot(x_test,self.coef_) + self.intercept_

In [ ]:
x_train.head(2)

           TV     Radio  Newspaper
79  -0.361572 -1.048306  -0.342262
197  0.348934 -0.940539  -1.109069

In [ ]:
gd = GDRegressor(epochs=100,learning_rate=0.3)

In [ ]:
gd.fit(x_train,y_train)

[1. 1. 1.] 0
epoch=0, coef=[2.97822504 1.73788918 0.69414594], intercept=8.471651837977642
epoch=1, coef=[3.6185502  2.17574013 0.51060985], intercept=11.825612325860828
epoch=2, coef=[3.80776149 2.42625105 0.3779445 ], intercept=13.15767110037567
epoch=3, coef=[3.85360274 2.57182079 0.28068771], intercept=13.688266506104574
epoch=4, coef=[3.85839977 2.65892715 0.21105239], intercept=13.900205647207935
epoch=5, coef=[3.85400972 2.71256341 0.16235157], intercept=13.985081528335819
epoch=6, coef=[3.84920823 2.7463585  0.12887883], intercept=14.019148788850643
epoch=7, coef=[3.84575367 2.7680122  0.10614617], intercept=14.032844981153136
epoch=8, coef=[3.84356223 2.78204811 0.09083142], intercept=14.038354173101096
epoch=9, coef=[3.84223775 2.79121691 0.08056955], intercept=14.04056705260523
epoch=10, coef=[3.84144918 2.79723691 0.07371823], intercept=14.041451670174125
epoch=11, coef=[3.84097864 2.80120259 0.06915499], intercept=14.041801575114755
epoch=12, coef=[3.8406947  2.80382059 0.06612062], intercept=14.041937085577581
epoch=13, coef=[3.84052074 2.8055513  0.06410508], intercept=14.041987429128042
epoch=14, coef=[3.84041246 2.80669647 0.06276726], intercept=14.042004567856903
epoch=15, coef=[3.84034408 2.80745464 0.06187971], intercept=14.042009226927942
epoch=16, coef=[3.84030036 2.80795678 0.06129107], intercept=14.042009536874906
epoch=17, coef=[3.84027213 2.80828943 0.06090077], intercept=14.042008585667851
epoch=18, coef=[3.84025377 2.80850984 0.060642  ], intercept=14.042007471664695
epoch=19, coef=[3.84024177 2.80865589 0.06047047], intercept=14.042006530342512
epoch=20, coef=[3.84023388 2.80875267 0.06035677], intercept=14.042005820913793
epoch=21, coef=[3.84022869 2.80881682 0.0602814 ], intercept=14.042005314535864
epoch=22, coef=[3.84022526 2.80885933 0.06023145], intercept=14.04200496355865
epoch=23, coef=[3.840223   2.8088875  0.06019834], intercept=14.042004724395358
epoch=24, coef=[3.8402215  2.80890617 0.06017639], intercept=14.042004563087064
epoch=25, coef=[3.84022051 2.80891855 0.06016185], intercept=14.04200445497708
epoch=26, coef=[3.84021985 2.80892675 0.06015221], intercept=14.042004382809147
epoch=27, coef=[3.84021942 2.80893218 0.06014582], intercept=14.042004334755951
epoch=28, coef=[3.84021913 2.80893579 0.06014158], intercept=14.042004302811558
epoch=29, coef=[3.84021894 2.80893817 0.06013878], intercept=14.042004281598079
epoch=30, coef=[3.84021881 2.80893976 0.06013692], intercept=14.042004267520301
epoch=31, coef=[3.84021873 2.80894081 0.06013569], intercept=14.042004258182075
epoch=32, coef=[3.84021867 2.8089415  0.06013487], intercept=14.042004251989528
epoch=33, coef=[3.84021864 2.80894196 0.06013433], intercept=14.042004247883778
epoch=34, coef=[3.84021861 2.80894227 0.06013397], intercept=14.042004245161943
epoch=35, coef=[3.84021859 2.80894247 0.06013373], intercept=14.042004243357697
epoch=36, coef=[3.84021858 2.8089426  0.06013357], intercept=14.042004242161765
epoch=37, coef=[3.84021858 2.80894269 0.06013347], intercept=14.042004241369076
epoch=38, coef=[3.84021857 2.80894275 0.0601334 ], intercept=14.04200424084368
epoch=39, coef=[3.84021857 2.80894279 0.06013335], intercept=14.042004240495448
epoch=40, coef=[3.84021857 2.80894282 0.06013332], intercept=14.042004240264646
epoch=41, coef=[3.84021857 2.80894283 0.0601333 ], intercept=14.042004240111673
epoch=42, coef=[3.84021856 2.80894284 0.06013329], intercept=14.042004240010286
epoch=43, coef=[3.84021856 2.80894285 0.06013328], intercept=14.04200423994309
epoch=44, coef=[3.84021856 2.80894286 0.06013327], intercept=14.042004239898553
epoch=45, coef=[3.84021856 2.80894286 0.06013327], intercept=14.042004239869035
epoch=46, coef=[3.84021856 2.80894286 0.06013327], intercept=14.042004239849472
epoch=47, coef=[3.84021856 2.80894286 0.06013327], intercept=14.042004239836505
epoch=48, coef=[3.84021856 2.80894287 0.06013326], intercept=14.04200423982791
epoch=49, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239822216
epoch=50, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239818441
epoch=51, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239815938
epoch=52, coef=[3.84021856 2.80894287 0.06013326], intercept=14.04200423981428
epoch=53, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239813181
epoch=54, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239812453
epoch=55, coef=[3.84021856 2.80894287 0.06013326], intercept=14.04200423981197
epoch=56, coef=[3.84021856 2.80894287 0.06013326], intercept=14.04200423981165
epoch=57, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811439
epoch=58, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811298
epoch=59, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811204
epoch=60, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811142
epoch=61, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811101
epoch=62, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811074
epoch=63, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811057
epoch=64, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811044
epoch=65, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811037
epoch=66, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811032
epoch=67, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811028
epoch=68, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811027
epoch=69, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811025
epoch=70, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811023
epoch=71, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811023
epoch=72, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811023
epoch=73, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811023
epoch=74, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811023
epoch=75, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=76, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=77, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=78, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=79, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=80, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=81, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=82, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=83, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=84, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=85, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=86, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=87, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=88, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=89, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=90, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=91, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=92, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=93, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=94, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=95, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=96, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=97, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=98, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021
epoch=99, coef=[3.84021856 2.80894287 0.06013326], intercept=14.042004239811021

In [ ]:
y_pred = gd.predict(x_test)

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

0.899438024100912

In [ ]:
sk_pred = 0.899438024100912
gd_pred = r2

if gd_pred > sk_pred:
  diff_gd = gd_pred - sk_pred
  print("GD working better:",diff_gd)
elif gd_pred < sk_pred:
  diff_sk = sk_pred - gd_pred
  print("sklearn model working better with",diff_sk)
else:
  print("No difference both got same score")

No difference both got same score